services:
  db:
    image: postgres:15
    container_name: laubank-db
    environment:
      - POSTGRES_USER=user_lau
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=laubank_db
    ports:
      - "5432:5432"